{pkgs}: {
  deps = [
    pkgs.unzip
    pkgs.xorg.libXfixes
    pkgs.xorg.libXdamage
    pkgs.xorg.libXcomposite
    pkgs.lacus
    pkgs.wayland
    pkgs.mesa
    pkgs.libdrm
    pkgs.xorg.libXext
    pkgs.xorg.libX11
    pkgs.chromium
    pkgs.alsa-lib
    pkgs.pango
    pkgs.expat
    pkgs.cups
    pkgs.atk
    pkgs.dbus
    pkgs.nspr
    pkgs.nss
    pkgs.playwright-driver
    pkgs.gitFull
    pkgs.qhull
    pkgs.gtk3
    pkgs.gobject-introspection
    pkgs.ghostscript
    pkgs.ffmpeg-full
    pkgs.cairo
    pkgs.geckodriver
    pkgs.zlib
    pkgs.tk
    pkgs.tcl
    pkgs.openjpeg
    pkgs.libwebp
    pkgs.libtiff
    pkgs.libjpeg
    pkgs.libimagequant
    pkgs.lcms2
    pkgs.freetype
    pkgs.wget
    pkgs.jq
    pkgs.postgresql
    pkgs.pkg-config
    pkgs.arrow-cpp
    pkgs.glibcLocales
    pkgs.rustc
    pkgs.libiconv
    pkgs.cargo
    pkgs.libxcrypt
    pkgs.bash
    pkgs.cacert
  ];
}
